### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by makc** [edcline/casmartadmin-lite#1]
@edcline could you please look into this:

![screen shot 2018-02-18 at 23 53 54](https://user-images.githubusercontent.com/242577/36358495-ae62d3ee-150f-11e8-9149-5a3c269ed42a.png)

I am using dummy data to work around this atm, but maybe it's better to tweak on server side.

**Comment by edcline** [comment]
I 'allowed all' for that api function on azure......let me know if you are still getting errors.

![image](https://user-images.githubusercontent.com/33406103/36360920-f9805316-14f5-11e8-9d0f-44bf58860209.png)

**Comment by makc** [comment]
Data is now getting in, thanks!
